version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: {{CONTAINER_PREFIX}}_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{DATABASE_NAME}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "{{DB_PORT}}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: {{CONTAINER_PREFIX}}_backend
    ports:
      - "{{BACKEND_PORT}}:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/{{DATABASE_NAME}}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: {{CONTAINER_PREFIX}}_frontend
    ports:
      - "{{FRONTEND_PORT}}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:{{BACKEND_PORT}}
    command: npm run dev

volumes:
  postgres_data:
