version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: {{CONTAINER_PREFIX}}_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{DATABASE_NAME}}_test
    ports:
      - "{{TEST_DB_PORT}}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # No volumes - we want a fresh database for each test run
