version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: test_gen_sample_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-gen-sample_db_test
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # No volumes - we want a fresh database for each test run
